### PR TITLE
Create zh.json

### PR DESCRIPTION
**Pull request by sscotti**
First submit of localizations for Chinese, I think HK, courtesy of ChatGPT, 'Franklin' and myself.   Franklin is on the Orthanc Forum also.

### CODE REVIEW

**Comment by sscotti** [comment]
There might be a few edits, but not many.  I wonder how ChatGPT does it.

**Comment by sscotti** [comment]
I just have the zh.json in the pull request, and then several others that I have in my Fork:

I take it I need to modify this also then:

image

Ming Zhang is in Shangdong Province in China, definitely a native speaker and seemingly motivated to contribute.

He installed it on his system, but I'll have to confirm that he verified the whole thing.  He texted me that on WhatsApp:

image

For the Netherlands I sent that off to someone I know who lives there, probably also on the Forum.  Ditto for Ukraine.

Salim doesn't know Arabic well enough.  He said he mostly speaks it.

I would think that some of you know German ?, attached.

The Ukrainian has corrections:

"delete_instance_title": "Видалити інстанцію?"
Patient: Study: Series: Instance

I'll have to followup about more so I won't submit another request.  I think the Chinese is good enough from what Ming  said, but he probably did not see them all in the UI, just the .json file.

[de.json.zip](https://github.com/orthanc-server/orthanc-explorer-2/files/11799008/de.json.zip)

**Comment by sscotti** [comment]
Ukraine I think is just ua.

Череднічок Юрій:  Cherednichok Yuriy, in Kyiv will get them to me tomorrow.

**Comment by sscotti** [comment]
Ukrainian is "українська"

**Comment by sscotti** [comment]
Українська (Capitalized)

**Comment by sscotti** [comment]
I have friends in Kyiv.

**Comment by sscotti** [comment]
If you want, I can just cancel the request and package it all up over then few days.

**Comment by amazy** [comment]
Please stop sending messages every 2 minutes, just issue a PR once it is fully complete.

**Comment by amazy** [comment]
Since I'm releasing right now, I have just added zh.json from this PR and uk.json from PR-17:
https://github.com/orthanc-server/orthanc-explorer-2/commit/5f5eaa5217581fc79a7354b2899639d91e248409

Thanks.

Alain.

**Comment by sscotti** [comment]
Thanks.  I'm kind of new to contributing via GitHub.  Can I continue to use my own Fork, or do you have a branch for that ?  It seems like they are sort of virtually the same.

**Pull request closed without merging**
